### ISSUE TITLE
PNGs without alpha channels are not loaded correctly

### ISSUE THREAD

**Issue by firesgc** [novuscore/NovusCore-Client#34]
Hey,

I think in 
"void TextureHandlerVK::LoadFile(const std::string& filename, Texture& texture, TextureID textureID)"
you must multiply the filesize all the time with 4 because stbi_load unpacks the texture to STBI_rgb_alpha.

Cheers,

**Comment by Pursche** [comment]
Good catch, I am pretty sure this was hardcoded to 4 previously but I must have mistakenly thought it looked wrong when refactoring. I will take a look at it this weekend! How did you find this issue, just reading code or did you try to load a png?

**Comment by firesgc** [comment]
Well, I use parts of the NovusCore-Client for a private project (the code of NovusCore is easy to read and it was way faster than starting from scratch) and parts of my UI were no longer rendered properly after I integrated to the latest version of the RenderLib.
NovusCore-Client is a really nice project.

**Comment by Pursche** [comment]
This should be fixed in commit dbeb635, thanks for reporting this and if you happen to be in our discord I would love to see what you're working on. This is the first time I've heard an outside project actually use any of our work, feel free to give us feedback on the useability and readability of our code. :)
